{% set version = "5.2.3" %}

package:
  name: xz
  version: {{ version }}

source:
  fn:  xz-{{ version }}.tar.bz2
  url: http://tukaani.org/xz/xz-{{ version }}.tar.gz
  sha256: 71928b357d0a09a12a4b4c5fafca8c31c19b0e7d3b8ebb19622e96f26dbf28cb

requirements:
  build:
    - {{ compiler('c') }} # [win]

test:
  commands:
    - xz --help  # [not win]
    - unxz --help  # [not win]
    - lzma --help  # [not win]
    # Note: no xz executable exists on windows right now - only libs.
    - if not exist %PREFIX%\\Library\\bin\\liblzma.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\liblzma.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\liblzma_static.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\lzma.h exit 1  # [win]
    # conda-inspect tests.
    #- conda inspect linkages -p $PREFIX xz  # [not win]
    #- conda inspect objects -p $PREFIX xz  # [osx]

about:
  home: http://tukaani.org/xz/
  license: LGPL-2.1 and GPL-2.0
  license_file: COPYING
  summary: Data compression software with high compression ratio
  description: |
    XZ Utils is free general-purpose data compression software with a high
    compression ratio. XZ Utils were written for POSIX-like systems, but also
    work on some not-so-POSIX systems.
  doc_url: http://tukaani.org/xz/
  doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
  dev_url: http://git.tukaani.org/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - mingwandroid
    - nehaljwani
