travis:
  secure:
    BINSTAR_TOKEN: lfKPCdVXHOWHTmZ5GtNLSsI4gbruU1R2aWGXd8zCXCBCAI/VgIJxPwJn4LMMKxa+xf8Ps+ycFz0ELzLJMtZX0RdkAJYW172okU4fuZsADCYVRnJj0BZ4oiaLQXhMkun2wr3mbdQLe2E9qMKGnakh58n2UEdKBaXmRIPQlDRmzAOVxdLbWgCcF2DJWLn7ogvxpe5DCbRwlVyeySLFccdTdSFPdR+PiknCILL8nSkJ/X4bmyuqneAtRUUvSI0cVVr+gxUP/NYkdYNt4s8xy8ZpJHqSyptc90ZMjP5BMRJqH19cNd5mvjoQQKTxjj1gdwDp+dwMAQC049No7TnnaeBQvyp9VWmAGMTuI7w34gHqtRN49Zt41T3v91OCbqgkJpyW/3Ka6r9vu/VufgZWw6C8OdAk6NK6KzNzHoB9KYPlNv8MMzCaRUjGF1S1lqOa7qIZKozjg352zorEudB1+8ShA4khsYUirjvX4NybWNGcuhBAryLD00I1cyekyFsQIEzsgmubxNFhyb/KuSwLgNkorv42HhwkTeFPiVeS4HxmrMPvG+HX3nPwh6hFPyjyzWrAlk4m0rWKrPokd/DGIKOO3CwLgMQgmvCCyOnQvsQfp/2EVQddwQs3Z1AjyOzaaUGHrXYiFgnn0TVWhefG8Fc9VjSOKcwrTn3VBpyw8c87M7c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
